model:
  size: "tiny" 
  #tiny, base, small, medium, large, large_v2
  #https://huggingface.co/openai/whisper-large-v2
  device: "cpu"
  chunk_length: "10"
  batch_size: 1
audio:
  path: "audio/trial_meeting.mp3"
transcript:
  save_loc: "transcripts/trial_meeting_transcript.txt"
    